name: pycrop_yield_prediction
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pandas
  - numpy
  - gdal
  - matplotlib
  - scipy
  - tqdm
  - fire
  - pytorch=1.0.0
  - earthengine-api
